#!/usr/bin/env python3
"""
gen_layout.py — generate every artifact derived from layout/keymap.py:

  firmware/scancode_map.h     SCANCODE[ROWS][COLS] for the firmware
  layout/keymap.svg           visual keymap diagram
  case/key_positions.scad     key centres for the OpenSCAD case
  kicad/key_positions.json    per-switch placement (mm) for the KiCad PCB

The KiCad netlist generator, tests/protocol_sim.py and the build123d case import
keymap.py directly, so they need no generated file. Run after editing keymap.py.
"""
import os, json, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import keymap as km

PITCH = 12.0          # key spacing (mm) — case + PCB must use the same value


def xml(s):
    return (s.replace("&", "&amp;").replace("<", "&lt;")
             .replace(">", "&gt;").replace('"', "&quot;"))


def gen_scancode_h():
    g = km.scancode_grid()
    out = ["/* AUTO-GENERATED by layout/gen_layout.py from layout/keymap.py — do not edit. */",
           "#pragma once",
           "/* Requires ROWS and COLS (== 8, 7) to be #defined before inclusion. */",
           "static const uint8_t SCANCODE[ROWS][COLS] PROGMEM = {"]
    for r in range(km.ROWS):
        out.append("    { " + ", ".join(f"0x{g[r][c]:02X}" for c in range(km.COLS)) + " },")
    out.append("};")
    p = os.path.join(ROOT, "firmware", "scancode_map.h")
    open(p, "w", newline="\n").write("\n".join(out) + "\n")
    return p


def gen_svg():
    U, gap, top = 50, 3, 26
    W = km.LAYOUT_COLS * U
    H = km.LAYOUT_ROWS * U + top
    s = [f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" font-family="monospace">',
         f'<rect width="{W}" height="{H}" fill="#161b22"/>',
         '<text x="6" y="17" fill="#9fb3c8" font-size="12">WorkBoy keymap — 53 keys, 8x7 matrix '
         '(label; scan code lower-right; matrix r,c upper-left)</text>']
    for i, k in enumerate(km.KEYS):
        x = k["x"] * U + gap
        y = k["y"] * U + gap + top
        w = k["w"] * U - 2 * gap
        h = U - 2 * gap
        r, c = km.matrix_rc(i)
        s.append(f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="6" fill="#21262d" stroke="#3d444d"/>')
        s.append(f'<text x="{x+w/2:.0f}" y="{y+h/2:.0f}" fill="#e6edf3" font-size="15" '
                 f'text-anchor="middle" dominant-baseline="central">{xml(k["label"])}</text>')
        s.append(f'<text x="{x+w-4:.0f}" y="{y+h-5:.0f}" fill="#7ee787" font-size="10" '
                 f'text-anchor="end">{k["code"]:02X}</text>')
        s.append(f'<text x="{x+4:.0f}" y="{y+12:.0f}" fill="#79c0ff" font-size="9">{r},{c}</text>')
    s.append("</svg>")
    p = os.path.join(HERE, "keymap.svg")
    open(p, "w", newline="\n").write("\n".join(s) + "\n")
    return p


def gen_scad():
    cs = km.centers(PITCH)
    out = ["// AUTO-GENERATED by layout/gen_layout.py — key centres (mm), origin = case centre.",
           f"pitch = {PITCH};",
           f"field_w = {km.LAYOUT_COLS * PITCH};",
           f"field_h = {km.LAYOUT_ROWS * PITCH};",
           "// [cx, cy, width_units]",
           "key_pos = ["]
    for cx, cy, w in cs:
        out.append(f"  [{cx:.3f}, {cy:.3f}, {w:.3f}],")
    out.append("];")
    p = os.path.join(ROOT, "case", "key_positions.scad")
    open(p, "w", newline="\n").write("\n".join(out) + "\n")
    return p


def gen_json():
    cs = km.centers(PITCH)
    data = {"pitch": PITCH,
            "field_w": km.LAYOUT_COLS * PITCH, "field_h": km.LAYOUT_ROWS * PITCH,
            "keys": [{"ref": f"SW{km.designator(i)}", "label": k["label"],
                      "code": k["code"], "x": round(cs[i][0], 3), "y": round(cs[i][1], 3),
                      "w": cs[i][2]} for i, k in enumerate(km.KEYS)]}
    p = os.path.join(ROOT, "kicad", "key_positions.json")
    json.dump(data, open(p, "w", newline="\n"), indent=1)
    return p


if __name__ == "__main__":
    for f in (gen_scancode_h, gen_svg, gen_scad, gen_json):
        print("wrote", os.path.relpath(f(), ROOT))
